In [31]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/dates_out.csv

In [32]:
import pandas as pd
df= pd.read_csv("../input/dates_out.csv")
df

,sentence,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 288,Unnamed: 289,Unnamed: 290,Unnamed: 291,Unnamed: 292,Unnamed: 293,Unnamed: 294,Unnamed: 295,Unnamed: 296,Unnamed: 297
0,seventeenth july,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,eight april,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24 september,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 May,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25 may,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,monday 26th of September,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297,monday seventeenth of november,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1298,thursday eighth of january,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1299,wednesday 20th of june,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1300,tuesday twenty eight of dec 2030,no,friday 20 of april 2025,s14,no,saturday six of December 2017,s14,no,wednesday twenty three of aug 2021,s14,...,s14,no,monday six of oct 2014,s14,no,wednesday six of october 2032,s14,no,saturday 7 of nov 2031,s

In [33]:
df["sentence"]= df["sentence"].str.lower()
df.head()

,sentence,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 288,Unnamed: 289,Unnamed: 290,Unnamed: 291,Unnamed: 292,Unnamed: 293,Unnamed: 294,Unnamed: 295,Unnamed: 296,Unnamed: 297
0,seventeenth july,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,eight april,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24 september,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 may,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25 may,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**401-500**

In [34]:
import re
import datetime
now = datetime.datetime.now()

weeks={'sunday':1,'monday':2,'tuesday':3,'wednesday':4,'thursday':5,'friday':6,'saturday':7}
dates={'day before yesterday':2,'previous':1,'next day':1,'a day before today':1,'yesterday':1,'this':0,'next week':7,'next to next':7,'today':0,'that':0,'one':1,'first':1,'next':1,'one':1,'day after today':1,'a day':1,'two':2,'second':2,'day after tomorrow':2,'a day after tomorrow':2,'three':3,'third':3,'little':3,'few':2,'four':4,'fourth':4,'some':4,'five':5,'fifth':5,'six':6,'sixth':6,'seven':7,'seventh':7,'after a week':7,'a week':7,'eight':8,'eighth':8,'nine':9,'nineth':9,'ten':10,'tenth':10,'eleven':11,'eleventh':11,'twelve':12,'twelfth':12,'thirteen':13,'thirteenth':13,'fourteenth':14,'fourteen':14,'fifteenth':15,'fifteen':15}

In [35]:
aks=402
for ii in df['sentence'][400:500]:
    me=ii
    add=0
    num=re.search(r'((^((previous|day\sbefore\syesterday|a\sday\sbefore\stoday|yesterday)|this|next\sweek|next\sday|next\sto\snext|that|one|first|next\sday|next|a\sday|second|two|day\safter\stomorrow|a\sday\safter\stomorrow|day\safter\stoday|little|few|third|three|some|four|fourth|five|fifth|six|sixth|seven|after\sa\sweek|seventh|a\sweek|eighth|eight|nine|nineth|ten|tenth|eleven|eleventh|twelve|twelfth|thirteen|thirteenth|fourteenth|fifteenth|today)\s(days|day)?)((\s?(later|after|(prior|before))?\s?((first|second|third|three)\s(day|days)\s)?(to|of)?\s*(sunday|monday|tuesday|wednesday|thursday|friday|saturday)(\s)*)$))',ii)
    if num:
        a=num.group(3) #num
        ext=num.group(11) #after of after
        before=num.group(9) #for before group
        bef=num.group(4)
        if ext:
            for l,m in dates.items():
                if l==ext:
                    add=add+m
                    #print(add)
            

        for l,m in dates.items():
            if l==a:
                add=add+m
                b=num.group(14) #saturday
                b=b.title()
                d = datetime.date.today()
                if b==d.strftime('%A'):
                    z=7
                    
                while d.strftime('%A') != b:
                    d+= datetime.timedelta(1)
                    #print(d)
                    
                if add==0:
                    aa=str(d)  
                
                elif before or bef:
                    s=1
                    add=add+s
                    add=1-add
                    d+=datetime.timedelta(add)
                    aa=str(d)
                
                else:
                    for i in range(0,add):
                        d+=datetime.timedelta(1)
                        aa=str(d)
                        
                  
                san=re.search(r'(([0-9]{4})(-)([0-9]{1,2})(-)([0-9]{1,2}))',aa)
                y=san.group(2)
                m=san.group(4)
                da=san.group(6)
                date=da+"-"+m+"-"+y
                ii=date
        
    print(ii,"///////////",me)
    aks=aks+1

27-03-2020 /////////// three days later tuesday
24-03-2020 /////////// five day later to thursday
26-03-2020 /////////// day after tomorrow tuesday
29-03-2020 /////////// three days after third day of monday
23-03-2020 /////////// four days later to thursday
27-03-2020 /////////// three days later tuesday
29-03-2020 /////////// eight day later of saturday
26-03-2020 /////////// eight day later of wednesday
26-03-2020 /////////// three days later monday
27-03-2020 /////////// little days later to tuesday
26-03-2020 /////////// fifth day after saturday
23-03-2020 /////////// previous to tuesday
21-03-2020 /////////// three days later wednesday
01-04-2020 /////////// ten days later sunday
02-04-2020 /////////// ten days later monday
27-03-2020 /////////// little days later to tuesday
24-03-2020 /////////// three days later saturday
31-03-2020 /////////// next week tuesday
23-03-2020 /////////// four day later of thursday
21-03-2020 /////////// next to friday
30-03-2020 /////////// after a week of monday
25-03-2020 /////////// six days later of thursday
26-03-2020 /////////// three day later monday
28-03-2020 /////////// five days later of monday
26-03-2020 /////////// two days later tuesday
next month same day sunday /////////// next month same day sunday
25-03-2020 /////////// six days after first day of wednesday
21-03-2020 /////////// few day later of thursday
21-03-2020 /////////// day after tomorrow thursday
24-03-2020 /////////// today tuesday
25-03-2020 /////////// fifth day after friday
19-03-2020 /////////// previous to friday
28-03-2020 /////////// a week later of saturday
24-03-2020 /////////// four days later to friday
22-03-2020 /////////// three day later thursday
31-03-2020 /////////// eight day later of monday
31-03-2020 /////////// six days after first day of tuesday
29-03-2020 /////////// five days later to tuesday
28-03-2020 /////////// three days after third day of sunday
27-03-2020 /////////// five days after third day of thursday
23-03-2020 /////////// day after today sunday
29-03-2020 /////////// six days later of monday
19-03-2020 /////////// few day prior of saturday
21-03-2020 /////////// few day prior of monday
23-03-2020 /////////// one days later of sunday
16-03-2020 /////////// few day prior of wednesday
27-03-2020 /////////// next to next friday
23-03-2020 /////////// five days later of wednesday
21-03-2020 /////////// day before yesterday monday
26-03-2020 /////////// some days later sunday
25-03-2020 /////////// one days later of tuesday
23-03-2020 /////////// a day prior to tuesday
24-03-2020 /////////// a day after tomorrow sunday
25-03-2020 /////////// six days later thursday
23-03-2020 /////////// some day later thursday
28-03-2020 /////////// seven days later saturday
22-03-2020 /////////// some days later wednesday
23-03-2020 /////////// this monday
25-03-2020 /////////// next to next wednesday
24-03-2020 /////////// little days later to saturday
21-03-2020 /////////// few days prior to monday
28-03-2020 /////////// seven days after second day of thursday
22-03-2020 /////////// a day after tomorrow friday
24-03-2020 /////////// three days later saturday
24-03-2020 /////////// little days later to saturday
29-03-2020 /////////// ten days after first day of wednesday
24-03-2020 /////////// five days later to thursday
24-03-2020 /////////// that tuesday
25-03-2020 /////////// day after tomorrow monday
25-03-2020 /////////// next day after tuesday
26-03-2020 /////////// day after tomorrow tuesday
25-03-2020 /////////// seven days later wednesday
six days later in march thursday /////////// six days later in march thursday
19-03-2020 /////////// previous to friday
20-03-2020 /////////// previous to saturday
25-03-2020 /////////// few days later of monday
30-03-2020 /////////// a week later of monday
26-03-2020 /////////// four days after first day of saturday
21-03-2020 /////////// a day after tomorrow thursday
22-03-2020 /////////// three day later thursday
28-03-2020 /////////// ten day later wednesday
28-03-2020 /////////// seven day later saturday
20-03-2020 /////////// few day prior of sunday
21-03-2020 /////////// yesterday sunday
19-03-2020 /////////// next to wednesday
22-03-2020 /////////// two day later friday
27-03-2020 /////////// three days later tuesday
23-03-2020 /////////// day after tomorrow saturday
26-03-2020 /////////// after a week of thursday
16-03-2020 /////////// few day prior of wednesday
26-03-2020 /////////// two days later tuesday
30-03-2020 /////////// eight days after first day of saturday
19-03-2020 /////////// a day before today friday
23-03-2020 /////////// day after tomorrow saturday
27-03-2020 /////////// one days after second day of tuesday
25-03-2020 /////////// six days later thursday
17-03-2020 /////////// few days prior to thursday
23-03-2020 /////////// five days later to wednesday
24-03-2020 /////////// four days later to friday
22-03-2020 /////////// a day before today monday

**501-600**

In [36]:
import re
import datetime
now = datetime.datetime.now()

month_day={1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
months={'january':1,'jan':1,'february':2,'feb':2,'march':3,'mar':3,'april':4,'apr':5,'may':5,'june':6,'jun':6,'july':7,'jul':7,'august':8,'aug':8,'september':9,'sept':9,'october':10,'oct':10,'november':11,'nov':11,'december':12,'dec':12}
weeks={'sunday':1,'monday':2,'tuesday':3,'wednesday':4,'thursday':5,'friday':6,'saturday':7}

day={'firstone':1,'two':2,'second':2,'three':3,'third':3,'four':4,'fourth':4,'fifth':5,'sixth':6,'six':6,'seven':7,'seventh':7,'eighth':8,'nine':9,'nineth':9,'nineteen':9,'ten':10,'twelveth':12,'twelve':12,'thirteen':13,'fourteenth':14,'fifteen':15,'fifteenth':15,'sixteen':16,'sixteenth':16,'seventeenth':17,'eighteen':18,'twentieth':20,'twenty first':21,'twenty one':21,'twenty second':22,'twenty two':22,'twenty third':23,'twenty four':24,'twenty six':26,'twenty nine':29}

dates={'day before yesterday':2,'previous':1,'next day':1,'a day before today':1,'yesterday':1,'this':0,'next week':7,'next to next':7,'today':0,'that':0,'one':1,'tomorrow':1,'first':1,'next':1,'one':1,'day after today':1,'a day':1,'two':2,'second':2,'day after tomorrow':2,'a day after tomorrow':2,'three':3,'third':3,'little':3,'few':2,'four':4,'fourth':4,'some':4,'five':5,'fifth':5,'six':6,'sixth':6,'seven':7,'seventh':7,'after a week':7,'a week':7,'eight':8,'eighth':8,'nine':9,'nineth':9,'ten':10,'tenth':10,'eleven':11,'eleventh':11,'twelve':12,'twelfth':12,'thirteen':13,'thirteenth':13,'fourteenth':14,'fourteen':14,'fifteenth':15,'fifteen':15}

In [37]:
def func(dic,val):
    for l,m in dic.items():
        if l==val:
            return m

In [38]:
aks=502
for ii in df['sentence'][500:600]:
    
    ori_mon = datetime.datetime.now().strftime("%m")
    ori_yr = datetime.datetime.now().strftime("%Y")
    #print(ii)
    me=ii
    add=0
    num=re.search(r'^((previous|day\sbefore\syesterday|a\sday\sbefore\stoday|yesterday)|this|that|next\sweek|next\sto\snext|one|first|next\sday|next|a\sday|second|two|day\safter\stomorrow|a\sday\safter\stomorrow|day\safter\stoday|little|few|third|three|some|four|fourth|five|fifth|six|sixth|seven|after\sa\sweek|seventh|a\sweek|eighth|eight|nine|nineth|ten|tenth|eleven|eleventh|twelve|twelfth|thirteen|thirteenth|fourteenth|fifteenth|today|tomorrow)\s(days|day)?\s?(after|later|(prior|before))?\s?((first|second|third)\s(days|day)\s)?(of|to|from|in)?\s?((first|one|two|second|three|third|four|fourth|fifth|sixth|six|seven|seventh|eighth|nine|nineth|nineteen|ten|twelveth|twelve|thirteen|fourteenth|fifteen|fifteenth|sixteen|sixteenth|seventeenth|eighteen|twentieth|twenty\sfirst|twenty\sone|twenty\ssecond|twenty\stwo|twenty\sthird|twenty\sfour|twenty\ssix|twenty\snine)?(\sday)?(([0-9]{1,2})(th|st|nd|rd)*)?\s(january|jan|february|feb|march|mar|april|apr|may|june|jun|july|jul|august|aug|september|sept|october|oct|november|nov|december|dec))$',ii)
    if num:
        mon=num.group(16) #to get months
        da=num.group(11) #to get date of twenty one
        danum=num.group(14)#get month day 5th
        ext=num.group(7) #extraa number added
        number=num.group(1)#number to added
        before=num.group(5)#before or prior
        befday=num.group(2)#yesterday or previous day
        
        
        
        if ext:
            m=func(dates,ext)
            add=add+m
            #print(ii,"---",add)
            
        if mon:#get month from dict
            m=func(months,mon)
            month=m
            #print(month)
            
        if da:#get day in numeric form
            m=func(day,da)
            days=int(m)
        elif danum:
            days=int(danum)
        
        if number:
            m=func(dates,number)
            add=add+m
        
        mont=int(ori_mon)
        yer=int(ori_yr)
        
        #year place
        if mont>month:
            yer=yer+1
        #print(yer)
        
        #checking leap year
        if (yer % 4) == 0:  
            if (yer % 100) == 0:  
                if (yer % 400) == 0:  
                       month_day[2]=29  
                else:  
                       month_day[2]=28
            else:  
                   month_day[2]=29  
        else:  
               month_day[2]=28
                
        if before or befday:
            days=days-add
            if days<0:
                if month==1:
                    month=12
                    yer=yer-1
                else:
                    month=month-1
                    
                mon_day=func(month_day,month)
                days=mon_day-days
        
        else:
            days=days+add
            mon_day=func(month_day,month)
             
            if days>mon_day:
                if month==12:
                    month=1
                    yer=yer+1
                else:
                    month=month+1
                    days=days-mon_day
                
#       print(ii,days,"-",month,"-",yer)
        days=str(days)
        month=str(month)
        year=str(yer)
        
        date=days+"-"+month+"-"+year
        print(date,"////////////",ii)
    aks=aks+1

11-1-2021 //////////// six day after 5 january
28-1-2021 //////////// ten days after first day of 17th january
6-1-2021 //////////// one day later of 5th january
5-10-2020 //////////// next week 28 september
26-9-2020 //////////// four day later of twenty second september
23-1-2021 //////////// seven days after second day of 14th jan
14-8-2020 //////////// nine day later to fifth august
16-6-2020 //////////// six days later ten june
11-2-2021 //////////// nine day later to two february
11-2-2021 //////////// tomorrow ten february
16-3-2020 //////////// five days later of 11th mar
17-5-2020 //////////// little day later to 14th apr
8-9-2020 //////////// that eighth sept
8-9-2020 //////////// six days later from 2nd sept
17-11-2020 //////////// tomorrow 16 november
17-5-2020 //////////// ten days after first day of sixth may
25-11-2020 //////////// previous to twenty six nov
14-9-2020 //////////// next day after thirteen september
18-8-2020 //////////// eight day later of 10th august
31-1-2021 //////////// day after tomorrow twenty nine january
9-9-2020 //////////// next to 8 september
28-10-2020 //////////// one days later of 27th october
19-5-2020 //////////// little day later to 16th may
23-7-2020 //////////// little days later to twentieth jul
10-5-2020 //////////// some day later sixth apr
19-10-2020 //////////// some days later fifteen october
25-7-2020 //////////// four days later to 21st jul
16-7-2020 //////////// next week nine jul
7-2-2021 //////////// little days later to four feb
30-3-2020 //////////// four days after first day of 25 mar
17-7-2020 //////////// little days later to 14th july
15-5-2020 //////////// eight day later of seven may
14-2-2021 //////////// a day before today fifteenth february
32-1-2021 //////////// day after tomorrow 30th december
20-4-2020 //////////// seven days later 13th april
11-11-2020 //////////// five days later to six nov
23-11-2020 //////////// two days after first day of twentieth nov
15-10-2020 //////////// five days after third day of seven oct
4-8-2020 //////////// little days later to 1 aug
18-2-2021 //////////// three days later 15 february
22-2-2021 //////////// six days later of 16 february
6-4-2020 //////////// four days later to 2 april
25-5-2020 //////////// two day later twenty third may
11-1-2021 //////////// ten days later 1st jan
24-11-2020 //////////// some days later 20th nov
7-9-2020 //////////// few days prior to nineth sept
10-2-2021 //////////// today ten feb
5-4-2020 //////////// nine day later to 27 march
17-9-2020 //////////// five days later to twelveth september
19-9-2020 //////////// next week twelveth september
11-5-2020 //////////// some days later seven may
24-2-2021 //////////// two days after first day of 21 february
29-5-2020 //////////// six day after twenty third may
26-1-2021 //////////// a day before today 27th jan
21-9-2020 //////////// three days later eighteen september
20-8-2020 //////////// four days later to sixteenth august
17-9-2020 //////////// four days after first day of twelve sept
2-8-2020 //////////// previous to three august
22-11-2020 //////////// that twenty second nov
8-5-2020 //////////// five days later to 3 may
12-2-2021 //////////// day after tomorrow 10th february
31-5-2020 //////////// ten day later twenty first apr
18-8-2020 //////////// six days after first day of 11th august
19-9-2020 //////////// ten day later nineteen sept
7-5-2020 //////////// two days after first day of fourth apr
31-12-2020 //////////// eight days after first day of twenty two december
24-5-2020 //////////// today 24th apr
4-10-2020 //////////// ten days after first day of twenty third sept
7-4-2020 //////////// few days prior to 9 april
12-8-2020 //////////// day after today 11th aug
30-3-2020 //////////// seven day later twenty third march
7-1-2021 //////////// one days after second day of four january
5-2-2021 //////////// day after today four feb
28-2-2021 //////////// some days later 24th february
33-1-2021 //////////// day after tomorrow 31 dec
24-2-2021 //////////// next to next 17th february
12-11-2020 //////////// a day after tomorrow 10th nov
13-1-2021 //////////// fifth day after 8th january
19-12-2020 //////////// six days later from thirteen december
31-8-2020 //////////// after a week of twenty four aug
3-9-2020 //////////// after a week of 27 aug
26-11-2020 //////////// four days after first day of twenty one nov
25-6-2020 //////////// three days later twenty two june
18-2-2021 //////////// six days later of 12th february
4-10-2020 //////////// tomorrow third oct
15-2-2021 //////////// one days later of fourteenth feb
3-11-2020 //////////// seven days later 27 october
18-3-2020 //////////// fifth day after 13th march
10-11-2020 //////////// three day later seventh nov
27-9-2020 //////////// few days prior to 29th sept
25-10-2020 //////////// four days later to 21st october
16-12-2020 //////////// a day prior to seventeenth december
27-1-2021 //////////// five days later to 22nd january
26-11-2020 //////////// five days later of twenty one november
6-2-2021 //////////// today sixth february
24-7-2020 //////////// eight day later of sixteen july
12-2-2021 //////////// ten days later two february

**601-900** same as previous code